# 26
SERVICES = ['Hotels_3', 'Flights_1', 'Buses_2', 'Movies_1', 'Homes_1',
            'Calendar_1', 'Hotels_1', 'Flights_2', 'Music_1', 'Services_1',
            'Services_3', 'RideSharing_1', 'Buses_1', 'Services_2', 'Media_1',
            'Events_2', 'Restaurants_1', 'Music_2', 'Events_1', 'RentalCars_1',
            'Hotels_2', 'Travel_1', 'Weather_1', 'Banks_1', 'RideSharing_2', 'RentalCars_2']
# dev: 'Restaurants_2', 'Alarm_1', 'Movies_2', 'Hotels_4', 'Flights_3', 'Services_4', 'Media_2', 'Banks_2'
# test: 'Events_3', 'Media_3', 'RentalCars_3', 'Services_4', 'Restaurants_2', 'Alarm_1',
#       'Messaging_1', 'Movies_3', 'Flights_4', 'Hotels_4', 'Music_3', 'Trains_1', 'Buses_3', 'Payment_1', 'Homes_2'

# 16
DOMAINS = {'RentalCars', 'Movies', 'Weather', 'Media', 'Homes', 'Flights', 'Hotels', 'Banks', 'Events', 'Buses',
           'Calendar', 'Music', 'RideSharing', 'Travel', 'Services', 'Restaurants'}
# dev: 'Alarm'
# test: 'Trains', 'Payment', 'Messaging', 'Alarm'


# 18
INTENTS = {'INFORM_INTENT', 'AFFIRM', 'INFORM', 'AFFIRM_INTENT', 'NEGATE', 'REQ_MORE', 'CONFIRM', 'NOTIFY_FAILURE',
           'INFORM_COUNT', 'SELECT', 'NOTIFY_SUCCESS', 'OFFER_INTENT', 'OFFER', 'REQUEST', 'THANK_YOU', 'GOODBYE',
           'NEGATE_INTENT', 'REQUEST_ALTS'}

# --Co-reference Slots
COREF = {
    'Flights': {'destination_airport_name': 'destination_airport',
                'flight_class': 'seating_class',
                'origin_airport_name': 'origin_airport',
                'number_of_tickets': 'passengers'},
    'Restaurants': {
        'category': 'cuisine',
        'location': 'street_address',
        'number_of_seats': 'party_size'
    },
    'Media': {
        'director': 'directed_by',
        'movie_name': 'title'
    },
    'Services': {
        'therapist_name': 'doctor_name'
    },
    'Movies': {
        'title': 'movie_name',
        'movie_title': 'movie_name',
        'number_of_tickets': 'count',
        'show_type': 'genre'
    },
    'Banks': {
        'account_balance': 'balance'
    },
    'Hotels': {
        'place_name': 'location'
    },
    'Buses': {
        'from_city': 'from_location',
        'to_city': 'to_location',
        'num_passengers': 'group_size'
    }
}

# 213
SLOTS = {
    'Restaurants': {'', 'count', 'serves_alcohol', 'cuisine', 'has_live_music', 'phone_number', 'intent', 'party_size',
                    'street_address', 'price_range', 'time', 'date', 'city', 'restaurant_name'},
    'Media': {'', 'count', 'genre', 'intent', 'subtitles', 'title', 'directed_by'},
    'Events': {'', 'venue', 'count', 'event_name', 'number_of_seats', 'intent', 'number_of_tickets', 'venue_address',
               'time', 'date', 'event_location', 'category', 'city_of_event', 'address_of_location', 'event_type',
               'city', 'subcategory'},
    'Music': {'', 'album', 'count', 'song_name', 'genre', 'intent', 'year', 'artist', 'playback_device'},
    'Movies': {'', 'count', 'genre', 'show_date', 'show_type', 'intent', 'show_time', 'movie_name', 'street_address',
               'theater_name', 'price', 'location'},
    'Flights': {'', 'seating_class', 'is_redeye', 'refundable', 'airlines', 'destination', 'inbound_departure_time',
                'price', 'intent', 'fare', 'destination_airport', 'outbound_arrival_time', 'outbound_departure_time',
                'destination_city', 'inbound_arrival_time', 'departure_date', 'count', 'origin_airport', 'origin',
                'number_stops', 'return_date', 'passengers', 'origin_city'},
    'RideSharing': {'', 'approximate_ride_duration', 'number_of_seats', 'ride_fare', 'intent', 'ride_type', 'wait_time',
                    'destination', 'number_of_riders', 'shared_ride'},
    'RentalCars': {'', 'car_name', 'pickup_date', 'count', 'dropoff_date', 'pickup_time', 'intent', 'pickup_city',
                   'type', 'total_price', 'pickup_location', 'car_type'},
    'Buses': {'', 'group_size', 'destination', 'price', 'destination_station_name', 'intent', 'fare', 'to_location',
              'departure_date', 'count', 'to_station', 'transfers', 'travelers', 'origin', 'departure_time',
              'from_station', 'leaving_date', 'from_location', 'leaving_time', 'fare_type', 'origin_station_name'},
    'Hotels': {'', 'check_in_date', 'hotel_name', 'has_laundry_service', 'number_of_days', 'destination', 'price',
               'location', 'has_wifi', 'price_per_night', 'intent', 'total_price', 'star_rating', 'rating',
               'number_of_rooms', 'number_of_adults', 'count', 'phone_number', 'street_address', 'address', 'where_to',
               'average_rating', 'pets_welcome', 'check_out_date'},
    'Services': {'', 'count', 'doctor_name', 'average_rating', 'dentist_name', 'phone_number', 'intent', 'stylist_name',
                 'is_unisex', 'appointment_time', 'street_address', 'type', 'offers_cosmetic_services', 'address',
                 'city', 'appointment_date'},
    'Homes': {'', 'area', 'count', 'rent', 'visit_date', 'address', 'number_of_beds', 'phone_number', 'intent',
              'property_name', 'number_of_baths', 'furnished', 'pets_allowed'},
    'Banks': {'', 'recipient_account_type', 'count', 'balance', 'intent', 'amount', 'recipient_account_name',
              'account_type'},
    'Calendar': {'', 'count', 'event_name', 'available_start_time', 'event_date', 'intent', 'available_end_time',
                 'event_location', 'event_time'},
    'Weather': {'', 'count', 'intent', 'humidity', 'precipitation', 'date', 'city', 'wind', 'temperature'},
    'Travel': {'', 'count', 'good_for_kids', 'phone_number', 'intent', 'attraction_name', 'free_entry', 'category',
               'location'}}

# 378
DA_FILTER = {'Restaurants': {'Restaurants-NOTIFY_FAILURE-', 'Restaurants-OFFER-date', 'Restaurants-REQUEST-city',
                             'Restaurants-REQUEST-restaurant_name', 'Restaurants-OFFER-restaurant_name',
                             'Restaurants-INFORM-street_address', 'Restaurants-REQ_MORE-',
                             'Restaurants-CONFIRM-restaurant_name', 'Restaurants-NOTIFY_SUCCESS-',
                             'Restaurants-INFORM-serves_alcohol', 'Restaurants-INFORM-price_range',
                             'Restaurants-OFFER-time', 'Restaurants-INFORM-cuisine', 'Restaurants-CONFIRM-city',
                             'Restaurants-OFFER-party_size', 'Restaurants-REQUEST-cuisine',
                             'Restaurants-INFORM_COUNT-count', 'Restaurants-CONFIRM-date', 'Restaurants-OFFER-city',
                             'Restaurants-INFORM-has_live_music', 'Restaurants-REQUEST-time',
                             'Restaurants-INFORM-phone_number', 'Restaurants-GOODBYE-', 'Restaurants-CONFIRM-time',
                             'Restaurants-CONFIRM-party_size', 'Restaurants-OFFER_INTENT-intent'},
             'Media': {'Media-REQUEST-title', 'Media-CONFIRM-title', 'Media-INFORM-directed_by', 'Media-INFORM-genre',
                       'Media-OFFER_INTENT-intent', 'Media-CONFIRM-subtitles', 'Media-REQUEST-genre',
                       'Media-INFORM_COUNT-count', 'Media-GOODBYE-', 'Media-OFFER-title', 'Media-NOTIFY_FAILURE-',
                       'Media-NOTIFY_SUCCESS-', 'Media-REQ_MORE-'},
             'Events': {'Events-CONFIRM-city_of_event', 'Events-REQUEST-city', 'Events-REQUEST-date',
                        'Events-NOTIFY_FAILURE-', 'Events-NOTIFY_SUCCESS-', 'Events-CONFIRM-number_of_seats',
                        'Events-REQUEST-number_of_tickets', 'Events-INFORM-venue_address', 'Events-CONFIRM-city',
                        'Events-INFORM-address_of_location', 'Events-OFFER_INTENT-intent', 'Events-CONFIRM-event_name',
                        'Events-INFORM-time', 'Events-REQUEST-event_name', 'Events-INFORM-category',
                        'Events-INFORM-venue', 'Events-INFORM-event_location', 'Events-OFFER-date',
                        'Events-INFORM_COUNT-count', 'Events-OFFER-venue', 'Events-REQUEST-category', 'Events-GOODBYE-',
                        'Events-REQUEST-city_of_event', 'Events-OFFER-event_location', 'Events-OFFER-time',
                        'Events-REQUEST-event_type', 'Events-CONFIRM-date', 'Events-INFORM-subcategory',
                        'Events-OFFER-event_name', 'Events-REQUEST-number_of_seats', 'Events-CONFIRM-number_of_tickets',
                        'Events-REQ_MORE-'},
             'Music': {'Music-OFFER-song_name', 'Music-NOTIFY_SUCCESS-', 'Music-REQUEST-song_name',
                       'Music-INFORM-genre', 'Music-CONFIRM-playback_device', 'Music-OFFER_INTENT-intent',
                       'Music-GOODBYE-', 'Music-INFORM-artist', 'Music-INFORM-year', 'Music-OFFER-artist',
                       'Music-OFFER-album', 'Music-NOTIFY_FAILURE-', 'Music-INFORM-album', 'Music-INFORM_COUNT-count',
                       'Music-CONFIRM-song_name', 'Music-REQ_MORE-'},
             'Movies': {'Movies-OFFER-show_time', 'Movies-REQUEST-show_date', 'Movies-INFORM_COUNT-count',
                        'Movies-OFFER-theater_name', 'Movies-INFORM-price', 'Movies-INFORM-street_address',
                        'Movies-REQUEST-movie_name', 'Movies-GOODBYE-', 'Movies-NOTIFY_FAILURE-', 'Movies-REQ_MORE-',
                        'Movies-OFFER_INTENT-intent', 'Movies-REQUEST-location', 'Movies-INFORM-genre',
                        'Movies-OFFER-movie_name'},
             'Flights': {'Flights-OFFER-number_stops', 'Flights-REQUEST-departure_date', 'Flights-REQUEST-origin',
                         'Flights-CONFIRM-passengers', 'Flights-CONFIRM-inbound_departure_time',
                         'Flights-INFORM-number_stops', 'Flights-INFORM-inbound_arrival_time',
                         'Flights-CONFIRM-departure_date', 'Flights-INFORM-passengers', 'Flights-INFORM-origin_airport',
                         'Flights-OFFER-departure_date', 'Flights-CONFIRM-destination_city',
                         'Flights-OFFER-inbound_departure_time', 'Flights-REQ_MORE-', 'Flights-CONFIRM-airlines',
                         'Flights-NOTIFY_SUCCESS-', 'Flights-REQUEST-destination', 'Flights-REQUEST-return_date',
                         'Flights-INFORM-refundable', 'Flights-GOODBYE-', 'Flights-CONFIRM-outbound_departure_time',
                         'Flights-INFORM-outbound_departure_time', 'Flights-INFORM-price', 'Flights-OFFER-airlines',
                         'Flights-INFORM-destination_airport', 'Flights-INFORM-is_redeye', 'Flights-OFFER-return_date',
                         'Flights-CONFIRM-seating_class', 'Flights-REQUEST-outbound_departure_time',
                         'Flights-CONFIRM-origin_city', 'Flights-OFFER-outbound_departure_time', 'Flights-OFFER-price',
                         'Flights-NOTIFY_FAILURE-', 'Flights-CONFIRM-return_date', 'Flights-REQUEST-airlines',
                         'Flights-REQUEST-origin_city', 'Flights-OFFER-fare', 'Flights-OFFER-destination_city',
                         'Flights-OFFER-origin_city', 'Flights-INFORM-outbound_arrival_time',
                         'Flights-OFFER_INTENT-intent', 'Flights-REQUEST-destination_city',
                         'Flights-INFORM-seating_class', 'Flights-REQUEST-inbound_departure_time',
                         'Flights-INFORM_COUNT-count'},
             'RideSharing': {'RideSharing-CONFIRM-destination', 'RideSharing-REQUEST-shared_ride',
                             'RideSharing-REQUEST-number_of_seats', 'RideSharing-REQUEST-number_of_riders',
                             'RideSharing-NOTIFY_SUCCESS-', 'RideSharing-CONFIRM-shared_ride',
                             'RideSharing-NOTIFY_FAILURE-', 'RideSharing-REQ_MORE-',
                             'RideSharing-CONFIRM-number_of_seats', 'RideSharing-REQUEST-destination',
                             'RideSharing-INFORM-approximate_ride_duration', 'RideSharing-INFORM-wait_time',
                             'RideSharing-GOODBYE-', 'RideSharing-INFORM-ride_fare', 'RideSharing-REQUEST-ride_type',
                             'RideSharing-CONFIRM-number_of_riders', 'RideSharing-CONFIRM-ride_type'},
             'RentalCars': {'RentalCars-INFORM-total_price', 'RentalCars-CONFIRM-pickup_location',
                            'RentalCars-OFFER-car_name', 'RentalCars-CONFIRM-pickup_time',
                            'RentalCars-OFFER-total_price', 'RentalCars-NOTIFY_FAILURE-',
                            'RentalCars-REQUEST-pickup_time', 'RentalCars-CONFIRM-type',
                            'RentalCars-REQUEST-dropoff_date', 'RentalCars-OFFER-pickup_date',
                            'RentalCars-REQUEST-car_type', 'RentalCars-REQUEST-pickup_date',
                            'RentalCars-OFFER_INTENT-intent', 'RentalCars-OFFER-car_type',
                            'RentalCars-CONFIRM-pickup_date', 'RentalCars-INFORM-car_name',
                            'RentalCars-INFORM_COUNT-count', 'RentalCars-REQUEST-pickup_city', 'RentalCars-OFFER-type',
                            'RentalCars-GOODBYE-', 'RentalCars-REQ_MORE-', 'RentalCars-CONFIRM-dropoff_date',
                            'RentalCars-CONFIRM-car_type', 'RentalCars-OFFER-pickup_location',
                            'RentalCars-NOTIFY_SUCCESS-', 'RentalCars-REQUEST-pickup_location',
                            'RentalCars-REQUEST-type'},
             'Buses': {'Buses-REQUEST-departure_time', 'Buses-INFORM-fare', 'Buses-INFORM_COUNT-count',
                       'Buses-CONFIRM-to_location', 'Buses-CONFIRM-departure_date', 'Buses-CONFIRM-from_location',
                       'Buses-CONFIRM-origin', 'Buses-INFORM-transfers', 'Buses-NOTIFY_FAILURE-',
                       'Buses-CONFIRM-departure_time', 'Buses-REQUEST-destination', 'Buses-OFFER-leaving_time',
                       'Buses-REQUEST-leaving_date', 'Buses-INFORM-origin_station_name', 'Buses-CONFIRM-destination',
                       'Buses-REQUEST-from_location', 'Buses-INFORM-destination_station_name',
                       'Buses-REQUEST-leaving_time', 'Buses-REQUEST-origin', 'Buses-NOTIFY_SUCCESS-',
                       'Buses-REQUEST-departure_date', 'Buses-REQ_MORE-', 'Buses-OFFER-departure_time',
                       'Buses-CONFIRM-leaving_time', 'Buses-CONFIRM-group_size', 'Buses-GOODBYE-',
                       'Buses-INFORM-from_station', 'Buses-REQUEST-group_size', 'Buses-INFORM-price',
                       'Buses-REQUEST-to_location', 'Buses-OFFER_INTENT-intent', 'Buses-CONFIRM-travelers',
                       'Buses-OFFER-transfers', 'Buses-INFORM-to_station', 'Buses-CONFIRM-leaving_date',
                       'Buses-CONFIRM-fare_type', 'Buses-OFFER-price', 'Buses-REQUEST-travelers',
                       'Buses-OFFER-fare_type', 'Buses-OFFER-fare'},
             'Hotels': {'Hotels-REQUEST-destination', 'Hotels-CONFIRM-number_of_adults', 'Hotels-INFORM-has_wifi',
                        'Hotels-OFFER-average_rating', 'Hotels-REQUEST-number_of_days', 'Hotels-CONFIRM-number_of_days',
                        'Hotels-INFORM-phone_number', 'Hotels-OFFER-hotel_name', 'Hotels-OFFER-star_rating',
                        'Hotels-OFFER-address', 'Hotels-CONFIRM-location', 'Hotels-OFFER_INTENT-intent',
                        'Hotels-REQUEST-check_out_date', 'Hotels-INFORM-rating', 'Hotels-REQUEST-location',
                        'Hotels-INFORM_COUNT-count', 'Hotels-CONFIRM-check_in_date', 'Hotels-INFORM-star_rating',
                        'Hotels-CONFIRM-hotel_name', 'Hotels-CONFIRM-where_to', 'Hotels-REQ_MORE-',
                        'Hotels-OFFER-rating', 'Hotels-REQUEST-check_in_date', 'Hotels-INFORM-destination',
                        'Hotels-REQUEST-number_of_adults', 'Hotels-OFFER-price_per_night',
                        'Hotels-CONFIRM-check_out_date', 'Hotels-INFORM-average_rating', 'Hotels-REQUEST-hotel_name',
                        'Hotels-INFORM-has_laundry_service', 'Hotels-INFORM-price', 'Hotels-REQUEST-where_to',
                        'Hotels-CONFIRM-destination', 'Hotels-INFORM-pets_welcome', 'Hotels-INFORM-price_per_night',
                        'Hotels-NOTIFY_FAILURE-', 'Hotels-INFORM-total_price', 'Hotels-GOODBYE-',
                        'Hotels-CONFIRM-number_of_rooms', 'Hotels-INFORM-street_address', 'Hotels-INFORM-address',
                        'Hotels-INFORM-location', 'Hotels-NOTIFY_SUCCESS-'},
             'Services': {'Services-OFFER-doctor_name', 'Services-CONFIRM-appointment_date',
                          'Services-REQUEST-appointment_time', 'Services-INFORM-offers_cosmetic_services',
                          'Services-REQUEST-city', 'Services-OFFER-type', 'Services-REQ_MORE-',
                          'Services-INFORM_COUNT-count', 'Services-CONFIRM-doctor_name', 'Services-NOTIFY_FAILURE-',
                          'Services-REQUEST-appointment_date', 'Services-CONFIRM-appointment_time',
                          'Services-INFORM-phone_number', 'Services-GOODBYE-', 'Services-INFORM-address',
                          'Services-INFORM-average_rating', 'Services-INFORM-city', 'Services-INFORM-is_unisex',
                          'Services-CONFIRM-stylist_name', 'Services-REQUEST-dentist_name', 'Services-REQUEST-type',
                          'Services-OFFER-appointment_time', 'Services-OFFER-dentist_name',
                          'Services-REQUEST-doctor_name', 'Services-OFFER_INTENT-intent', 'Services-INFORM-type',
                          'Services-CONFIRM-dentist_name', 'Services-NOTIFY_SUCCESS-', 'Services-REQUEST-stylist_name',
                          'Services-OFFER-appointment_date', 'Services-OFFER-stylist_name', 'Services-OFFER-city',
                          'Services-INFORM-street_address'},
             'Homes': {'Homes-REQUEST-visit_date', 'Homes-REQUEST-area', 'Homes-INFORM-pets_allowed',
                       'Homes-INFORM-furnished', 'Homes-OFFER-number_of_beds', 'Homes-GOODBYE-', 'Homes-REQ_MORE-',
                       'Homes-CONFIRM-visit_date', 'Homes-INFORM-phone_number', 'Homes-NOTIFY_FAILURE-',
                       'Homes-OFFER-property_name', 'Homes-OFFER-address', 'Homes-OFFER_INTENT-intent',
                       'Homes-REQUEST-number_of_beds', 'Homes-OFFER-number_of_baths', 'Homes-NOTIFY_SUCCESS-',
                       'Homes-CONFIRM-property_name', 'Homes-INFORM_COUNT-count', 'Homes-OFFER-rent'},
             'Banks': {'Banks-REQ_MORE-', 'Banks-REQUEST-account_type', 'Banks-REQUEST-recipient_account_name',
                       'Banks-CONFIRM-recipient_account_type', 'Banks-OFFER-account_type',
                       'Banks-CONFIRM-recipient_account_name', 'Banks-CONFIRM-account_type', 'Banks-REQUEST-amount',
                       'Banks-GOODBYE-', 'Banks-OFFER_INTENT-intent', 'Banks-INFORM_COUNT-count',
                       'Banks-NOTIFY_SUCCESS-', 'Banks-CONFIRM-amount', 'Banks-NOTIFY_FAILURE-', 'Banks-OFFER-balance'},
             'Calendar': {'Calendar-REQUEST-event_name', 'Calendar-CONFIRM-event_date', 'Calendar-NOTIFY_SUCCESS-',
                          'Calendar-OFFER-event_date', 'Calendar-OFFER-available_start_time', 'Calendar-REQ_MORE-',
                          'Calendar-CONFIRM-event_time', 'Calendar-OFFER-available_end_time',
                          'Calendar-OFFER_INTENT-intent', 'Calendar-OFFER-event_time', 'Calendar-REQUEST-event_time',
                          'Calendar-OFFER-event_name', 'Calendar-REQUEST-event_location', 'Calendar-CONFIRM-event_name',
                          'Calendar-REQUEST-event_date', 'Calendar-CONFIRM-event_location',
                          'Calendar-INFORM_COUNT-count', 'Calendar-GOODBYE-', 'Calendar-NOTIFY_FAILURE-'},
             'Weather': {'Weather-INFORM-humidity', 'Weather-NOTIFY_FAILURE-', 'Weather-OFFER-temperature',
                         'Weather-REQ_MORE-', 'Weather-INFORM-wind', 'Weather-OFFER-precipitation',
                         'Weather-INFORM_COUNT-count', 'Weather-INFORM-date', 'Weather-REQUEST-city'},
             'Travel': {'Travel-OFFER-attraction_name', 'Travel-NOTIFY_FAILURE-', 'Travel-INFORM-free_entry',
                        'Travel-REQ_MORE-', 'Travel-REQUEST-location', 'Travel-OFFER-category',
                        'Travel-INFORM-good_for_kids', 'Travel-GOODBYE-', 'Travel-INFORM_COUNT-count',
                        'Travel-INFORM-phone_number'}}

# 318
DAU_FILTER = {
    'Restaurants': {'Restaurants-AFFIRM_INTENT-', 'Restaurants-REQUEST-serves_alcohol', 'Restaurants-INFORM-date',
                    'Restaurants-INFORM_INTENT-intent', 'Restaurants-SELECT-', 'Restaurants-INFORM-serves_alcohol',
                    'Restaurants-NEGATE_INTENT-', 'Restaurants-THANK_YOU-', 'Restaurants-INFORM-price_range',
                    'Restaurants-NEGATE-', 'Restaurants-INFORM-cuisine', 'Restaurants-REQUEST-price_range',
                    'Restaurants-REQUEST-phone_number', 'Restaurants-AFFIRM-', 'Restaurants-REQUEST-cuisine',
                    'Restaurants-INFORM-restaurant_name', 'Restaurants-INFORM-has_live_music',
                    'Restaurants-REQUEST-has_live_music', 'Restaurants-INFORM-time', 'Restaurants-REQUEST_ALTS-',
                    'Restaurants-INFORM-city', 'Restaurants-GOODBYE-', 'Restaurants-INFORM-party_size',
                    'Restaurants-REQUEST-street_address'},
    'Media': {'Media-REQUEST_ALTS-', 'Media-INFORM-directed_by', 'Media-SELECT-title', 'Media-THANK_YOU-',
              'Media-REQUEST-directed_by', 'Media-AFFIRM_INTENT-', 'Media-INFORM-subtitles', 'Media-REQUEST-genre',
              'Media-INFORM_INTENT-intent', 'Media-NEGATE_INTENT-', 'Media-AFFIRM-', 'Media-NEGATE-',
              'Media-INFORM-genre', 'Media-INFORM-title', 'Media-GOODBYE-'},
    'Events': {'Events-INFORM-date', 'Events-REQUEST-venue_address', 'Events-REQUEST-subcategory',
               'Events-AFFIRM_INTENT-', 'Events-NEGATE-', 'Events-REQUEST-address_of_location',
               'Events-INFORM-number_of_tickets', 'Events-SELECT-', 'Events-INFORM-event_name', 'Events-INFORM-city',
               'Events-AFFIRM-', 'Events-REQUEST-venue', 'Events-INFORM-category', 'Events-REQUEST-time',
               'Events-REQUEST-event_location', 'Events-INFORM-event_type', 'Events-INFORM-city_of_event',
               'Events-REQUEST-category', 'Events-GOODBYE-', 'Events-INFORM-number_of_seats',
               'Events-INFORM-subcategory', 'Events-REQUEST_ALTS-', 'Events-INFORM_INTENT-intent', 'Events-THANK_YOU-',
               'Events-NEGATE_INTENT-'},
    'Music': {'Music-INFORM-playback_device', 'Music-REQUEST-album', 'Music-REQUEST-genre', 'Music-AFFIRM_INTENT-',
              'Music-INFORM-genre', 'Music-REQUEST-artist', 'Music-GOODBYE-', 'Music-INFORM-artist', 'Music-AFFIRM-',
              'Music-INFORM-year', 'Music-INFORM-song_name', 'Music-THANK_YOU-', 'Music-REQUEST-year',
              'Music-REQUEST_ALTS-', 'Music-INFORM-album', 'Music-INFORM_INTENT-intent', 'Music-NEGATE-',
              'Music-SELECT-'},
    'Movies': {'Movies-INFORM-location', 'Movies-INFORM-show_date', 'Movies-REQUEST_ALTS-', 'Movies-SELECT-movie_name',
               'Movies-NEGATE_INTENT-', 'Movies-AFFIRM-', 'Movies-REQUEST-price', 'Movies-GOODBYE-', 'Movies-NEGATE-',
               'Movies-REQUEST-street_address', 'Movies-INFORM-genre', 'Movies-INFORM-movie_name',
               'Movies-REQUEST-genre', 'Movies-INFORM-show_type', 'Movies-INFORM-theater_name',
               'Movies-INFORM_INTENT-intent', 'Movies-SELECT-', 'Movies-THANK_YOU-'},
    'Flights': {'Flights-INFORM_INTENT-intent', 'Flights-REQUEST-outbound_arrival_time', 'Flights-SELECT-',
                'Flights-INFORM-airlines', 'Flights-INFORM-destination_city', 'Flights-REQUEST-inbound_arrival_time',
                'Flights-NEGATE_INTENT-', 'Flights-INFORM-destination', 'Flights-REQUEST-refundable',
                'Flights-INFORM-return_date', 'Flights-INFORM-passengers', 'Flights-REQUEST-is_redeye',
                'Flights-REQUEST-number_stops', 'Flights-INFORM-refundable', 'Flights-GOODBYE-', 'Flights-NEGATE-',
                'Flights-INFORM-outbound_departure_time', 'Flights-INFORM-inbound_departure_time',
                'Flights-REQUEST-outbound_departure_time', 'Flights-REQUEST-seating_class', 'Flights-THANK_YOU-',
                'Flights-INFORM-departure_date', 'Flights-REQUEST-passengers', 'Flights-REQUEST_ALTS-',
                'Flights-REQUEST-origin_airport', 'Flights-REQUEST-destination_airport', 'Flights-AFFIRM_INTENT-',
                'Flights-REQUEST-price', 'Flights-INFORM-seating_class', 'Flights-AFFIRM-',
                'Flights-INFORM-origin_city', 'Flights-INFORM-origin'},
    'RideSharing': {'RideSharing-INFORM-shared_ride', 'RideSharing-THANK_YOU-', 'RideSharing-INFORM-number_of_riders',
                    'RideSharing-INFORM_INTENT-intent', 'RideSharing-REQUEST-approximate_ride_duration',
                    'RideSharing-INFORM-ride_type', 'RideSharing-REQUEST-wait_time', 'RideSharing-AFFIRM-',
                    'RideSharing-GOODBYE-', 'RideSharing-INFORM-destination', 'RideSharing-INFORM-number_of_seats',
                    'RideSharing-REQUEST-ride_fare', 'RideSharing-NEGATE-'},
    'RentalCars': {'RentalCars-REQUEST-car_name', 'RentalCars-INFORM-pickup_date', 'RentalCars-SELECT-',
                   'RentalCars-INFORM-pickup_city', 'RentalCars-NEGATE_INTENT-', 'RentalCars-AFFIRM-',
                   'RentalCars-INFORM-pickup_time', 'RentalCars-REQUEST-total_price', 'RentalCars-NEGATE-',
                   'RentalCars-INFORM-type', 'RentalCars-INFORM-dropoff_date', 'RentalCars-REQUEST_ALTS-',
                   'RentalCars-INFORM-pickup_location', 'RentalCars-INFORM-car_type', 'RentalCars-INFORM_INTENT-intent',
                   'RentalCars-THANK_YOU-', 'RentalCars-GOODBYE-', 'RentalCars-AFFIRM_INTENT-'},
    'Buses': {'Buses-REQUEST-origin_station_name', 'Buses-REQUEST-fare', 'Buses-REQUEST_ALTS-',
              'Buses-REQUEST-transfers', 'Buses-NEGATE_INTENT-', 'Buses-INFORM-group_size', 'Buses-INFORM-origin',
              'Buses-INFORM-departure_date', 'Buses-INFORM-to_location', 'Buses-INFORM-travelers',
              'Buses-REQUEST-destination_station_name', 'Buses-INFORM-leaving_time', 'Buses-INFORM-fare_type',
              'Buses-INFORM-from_location', 'Buses-AFFIRM_INTENT-', 'Buses-INFORM-departure_time',
              'Buses-REQUEST-to_station', 'Buses-INFORM-leaving_date', 'Buses-SELECT-', 'Buses-GOODBYE-',
              'Buses-REQUEST-from_station', 'Buses-THANK_YOU-', 'Buses-REQUEST-price', 'Buses-AFFIRM-',
              'Buses-INFORM_INTENT-intent', 'Buses-NEGATE-', 'Buses-INFORM-destination'},
    'Hotels': {'Hotels-REQUEST-destination', 'Hotels-INFORM-has_wifi', 'Hotels-REQUEST-has_wifi',
               'Hotels-INFORM-hotel_name', 'Hotels-REQUEST-price', 'Hotels-REQUEST-phone_number',
               'Hotels-INFORM-number_of_rooms', 'Hotels-AFFIRM_INTENT-', 'Hotels-REQUEST_ALTS-', 'Hotels-THANK_YOU-',
               'Hotels-REQUEST-rating', 'Hotels-INFORM-number_of_days', 'Hotels-INFORM-check_out_date',
               'Hotels-REQUEST-average_rating', 'Hotels-REQUEST-price_per_night', 'Hotels-INFORM-location',
               'Hotels-INFORM-rating', 'Hotels-REQUEST-location', 'Hotels-REQUEST-address',
               'Hotels-INFORM-check_in_date', 'Hotels-AFFIRM-', 'Hotels-SELECT-', 'Hotels-INFORM-star_rating',
               'Hotels-INFORM-where_to', 'Hotels-REQUEST-street_address', 'Hotels-REQUEST-total_price',
               'Hotels-INFORM-destination', 'Hotels-REQUEST-star_rating', 'Hotels-NEGATE_INTENT-',
               'Hotels-INFORM-has_laundry_service', 'Hotels-REQUEST-pets_welcome', 'Hotels-REQUEST-has_laundry_service',
               'Hotels-INFORM-pets_welcome', 'Hotels-INFORM_INTENT-intent', 'Hotels-GOODBYE-',
               'Hotels-INFORM-number_of_adults', 'Hotels-NEGATE-'},
    'Services': {'Services-AFFIRM-', 'Services-INFORM-dentist_name', 'Services-INFORM-offers_cosmetic_services',
                 'Services-REQUEST-average_rating', 'Services-REQUEST-phone_number', 'Services-REQUEST-city',
                 'Services-NEGATE-', 'Services-REQUEST-address', 'Services-AFFIRM_INTENT-', 'Services-GOODBYE-',
                 'Services-INFORM-city', 'Services-INFORM_INTENT-intent', 'Services-REQUEST-is_unisex',
                 'Services-INFORM-is_unisex', 'Services-INFORM-appointment_date',
                 'Services-REQUEST-offers_cosmetic_services', 'Services-SELECT-', 'Services-REQUEST-type',
                 'Services-INFORM-type', 'Services-NEGATE_INTENT-', 'Services-INFORM-appointment_time',
                 'Services-INFORM-stylist_name', 'Services-INFORM-doctor_name', 'Services-THANK_YOU-',
                 'Services-REQUEST_ALTS-', 'Services-REQUEST-street_address'},
    'Homes': {'Homes-INFORM-number_of_baths', 'Homes-INFORM-visit_date', 'Homes-REQUEST_ALTS-',
              'Homes-INFORM-number_of_beds', 'Homes-NEGATE_INTENT-', 'Homes-AFFIRM_INTENT-',
              'Homes-INFORM-pets_allowed', 'Homes-NEGATE-', 'Homes-AFFIRM-', 'Homes-THANK_YOU-',
              'Homes-INFORM-furnished', 'Homes-REQUEST-furnished', 'Homes-INFORM_INTENT-intent', 'Homes-INFORM-area',
              'Homes-SELECT-', 'Homes-REQUEST-pets_allowed', 'Homes-GOODBYE-', 'Homes-REQUEST-phone_number'},
    'Banks': {'Banks-THANK_YOU-', 'Banks-INFORM-recipient_account_type', 'Banks-NEGATE_INTENT-',
              'Banks-INFORM-account_type', 'Banks-REQUEST_ALTS-', 'Banks-AFFIRM_INTENT-', 'Banks-INFORM_INTENT-intent',
              'Banks-GOODBYE-', 'Banks-NEGATE-', 'Banks-INFORM-amount', 'Banks-AFFIRM-', 'Banks-SELECT-',
              'Banks-INFORM-recipient_account_name'},
    'Calendar': {'Calendar-AFFIRM-', 'Calendar-AFFIRM_INTENT-', 'Calendar-INFORM-event_name',
                 'Calendar-INFORM-event_date', 'Calendar-GOODBYE-', 'Calendar-REQUEST_ALTS-', 'Calendar-SELECT-',
                 'Calendar-THANK_YOU-', 'Calendar-NEGATE_INTENT-', 'Calendar-INFORM-event_time',
                 'Calendar-INFORM_INTENT-intent', 'Calendar-NEGATE-', 'Calendar-INFORM-event_location'},
    'Weather': {'Weather-SELECT-', 'Weather-REQUEST-wind', 'Weather-INFORM_INTENT-intent', 'Weather-REQUEST-date',
                'Weather-REQUEST-humidity', 'Weather-REQUEST_ALTS-', 'Weather-INFORM-date', 'Weather-INFORM-city'},
    'Travel': {'Travel-INFORM-location', 'Travel-INFORM-free_entry', 'Travel-REQUEST-good_for_kids',
               'Travel-REQUEST-free_entry', 'Travel-INFORM-category', 'Travel-NEGATE-', 'Travel-INFORM_INTENT-intent',
               'Travel-THANK_YOU-', 'Travel-REQUEST_ALTS-', 'Travel-SELECT-', 'Travel-INFORM-good_for_kids',
               'Travel-GOODBYE-', 'Travel-REQUEST-phone_number'}}
